### ISSUE TITLE
TU breaks 'Classic Theme Restorer" add-ons squared tabs and removes CTRs menu entries in Tools menu and submenu

### ISSUE THREAD

**Issue by Aris-t2** [ithinc/tabutils#49]
Hello ithinc,
I have tested latest final and beta releases of TabUtilities with my add-on "Classic Theme Restorer". For some reason it breaks CTRs pinned tabs positions and also removes CTRs menu entries in Tools menu and options submenu of the appmenu button for no reason.

Could you look into it?

**Comment by ithinc** [comment]
Version?

**Comment by Aris-t2** [comment]
Sorry, I haven't specified versions, because it happened with all of them, but here are more details of what I have tested after a user of CTR informed me about the incompatibility.

Classic Theme Restorer 1.1.6 and 1.1.7
TabUtilities 1.5.27, 1.5.28 & 1.6pre21
Firefox 29-31
(only tested on Windows 7 atm)

**Comment by ithinc** [comment]
Why do you use collapsed="true" for the two menu entries? TU has a global css rule to hide all collapsed menuitems.

**Comment by ithinc** [comment]
For pinned tab positions, I have no idea what you mean. It's better to have a screenshot.

**Comment by Aris-t2** [comment]
I will look into the 'collapsed' entry and why I have added them.

Pinned tabs
http://i58.tinypic.com/2ef5d37.png

**Comment by ithinc** [comment]
Got it. Do you have some steps to reproduce it?

**Comment by Aris-t2** [comment]
Select 'squared tabs' on CTRs prefwindow and pin a tab. Then it already happens.

**Comment by Aris-t2** [comment]
I fixed the 'disappearing menuitems'  issue.

**Comment by ithinc** [comment]
Good news. Why do you override the following rule?

``` CSS
.tabbrowser-arrowscrollbox > .arrowscrollbox-scrollbox {
  -moz-padding-start: 0px !important;
}
```

TU is dynamically detecting a similar rule in browser.css, but overridden by CTR.

**Comment by Aris-t2** [comment]
To remove the gap between tab toolbars left border and first tab.

**Comment by ithinc** [comment]
Could you use some negative margin to eliminate the extra padding? 
It was a TU hack on Mac platform on Fx4+ to eliminate gap between TU Phantom tabs and Normal tabs, and additionally move the padding to the very beginning to the whole tabs toolbar.

**Comment by Aris-t2** [comment]
I will look into it.

Is your hack still required for Fx29+ on Mac and why does it affect Windows too?

**Comment by ithinc** [comment]
I have not looked into Fx29+. I'm not sure yet. The old rule in browser.css appears only on Mac, but I didn't care about OS when detecting. So it's affecting Windows also.

The following rule works, as I just tested.

``` CSS
.tabbrowser-arrowscrollbox {
  -moz-margin-start: -15px;
}
```

**Comment by Aris-t2** [comment]
There are way to many cases ;-)

The rule does hide the left scrollbox arrow, if TU is disabled.

**Comment by ithinc** [comment]
Why that happen? Do you disable the 0px!important padding rule?

**Comment by Aris-t2** [comment]
Yes I have.

There is probably another solution. 

Testing this one right now:

#tabbrowser-tabs  {
  margin-left: -15px !important;
}

**Comment by Aris-t2** [comment]
Nope doesn't work, if TU is disabled and there are no pinned tabs.

**Comment by ithinc** [comment]
Then just leave it aside for a while. At least the cause is clear now.

**Comment by ithinc** [comment]
What about this one?

``` CSS
.tabbrowser-tab:first-of-type {
-moz-margin-start: -15px;
}
.tabbrowser-tab:last-of-type {
-moz-margin-end: -15px;
}
```

**Comment by ithinc** [comment]
Otherwise, if you want to touch TU internal element, you may add some TU-specific rules, like:

``` CSS
#PinnedTabsBarItems {
-moz-padding-start: 0px !important; /* Corresponding to 0px padding-start */
-moz-padding-end: 0px !important; /* Corresponding to 0px padding-end instead of margin-right: -15px for new-tab-button, which won't work in overflow mode */
-moz-margin-end: 0px !important; /* Corresponding to 0px padding-end */
}
.tabbrowser-arrowscrollbox > .arrowscrollbox-scrollbox {
-moz-margin-start: 0px !important; /* Corresponding to 0px padding-start */
}
```

These should only be working with the 0px!important padding rule.
