### ISSUE TITLE
标签页图标问题，有些网站无图标，貌似导致不会显示空白图标！

### ISSUE THREAD

**Issue by dsyo2008** [ithinc/tabutils#63]
应该是这TU扩展，禁用后可以显示空白图标，启用后无空白图标，变成标题。。。。
[img]http://i.picpar.com/ZNF.jpg[/img]

**Comment by ithinc** [comment]
新建配置文件测试。

**Comment by dsyo2008** [comment]
试过正常。。。新建配置有空白图标！启用TU后无空白图标

**Comment by ithinc** [comment]
操作系统、Firefox、TU版本？对比截图？

**Comment by dsyo2008** [comment]
win7 x64 
firefox 31每夜 
Tab Utilities 1.6pre21

---

不好意思，我搞错了！原来是每夜问题，应该是关闭空白图标

**Comment by ithinc** [comment]
Introduced by [Bug 685059 – Remove empty placeholder icon when a page has no favicon](https://bugzilla.mozilla.org/show_bug.cgi?id=685059).

**Comment by dsyo2008** [comment]
原来是这个原因。。。。有没加空白图标方法？看了不爽，求方法！

**Comment by ithinc** [comment]
``` CSS
.tab-throbber:not([busy]) + .tab-icon-image {
  display: -moz-box !important;
}
```
